name: '@cartogram/deepl-translate-action'
description: 'Translate text using DeepL API'
author: 'Matt Seccafien'
inputs:
  languageDirectory:
    description: 'Path to a directory in which you will recursively find all JSON files named [from].json (e.g. en.json)'
    default: '/'
  sourceLanguage:
    description: 'Source language'
    required: true
    default: 'en'
  targetLanguage:
    description: 'Target language'
    required: true
  authKey:
    description: 'DeepL API auth key'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
