name: '@cartogram/deepl-translate-action'
description: 'Translate text using DeepL API'
author: 'Matt Seccafien'
inputs:
  languageFilesDirectory:
    description: 'Path to a directory in which you will recursively find all JSON files named [from].json (e.g. en.json). Either filePath or dirPath is required'
    default: '/'
  sourceLange:
    description: 'Source language'
    required: true
  targetLang:
    description: 'Target language'
    required: true
  authKey:
    description: 'DeepL API auth key'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
